### ISSUE TITLE
Missing some class end with "_incremental"

### ISSUE THREAD

**Issue by cuongnguyengit** [WilliamsToTo/IMG#1]
Hello. Very interesting article. I want to test them on my data but I see that in your code there are a few classes that don't seem to be implemented yet.

**Comment by WilliamsToTo** [comment]
Thanks for your feedback. I updated the model folder. Classes with postfix "_incremental" are implemented in new files.

**Comment by cuongnguyengit** [comment]
I have a more question. For multiclass, i don't understand why you need
backbone model instead of init into init function like others?

Backbone is still trained and if it is variable of forward function,
whether it is saved with the model?

Vào Th 4, 29 thg 5, 2024 lúc 08:43 WilliamsToTo ***@***.***>
đã viết:

**Comment by WilliamsToTo** [comment]
From what I understand, if the backbone model's parameters are not included in the optimizer, they will not be trained. I have designed the forward function to accept the backbone model as an argument specifically to ensure that only the mask layers are saved, thereby saving disk space. In binary classification scenarios, I include the backbone model in the __init__ function and freeze its parameters. However, this approach results in both the backbone model and the mask layers being saved, which costs more disk space.

**Comment by cuongnguyengit** [comment]
Ok its for saving space. Thank you for explanation.

Vào Th 4, 29 thg 5, 2024 lúc 14:19 WilliamsToTo ***@***.***>
đã viết:

**Comment by WilliamsToTo** [comment]
Thanks for your interest in this project. 😊

**Comment by cuongnguyengit** [comment]
Should Backbone model be still freezed to save gpu computation and memory?

**Comment by WilliamsToTo** [comment]
You can give it a try. From my understanding, whether the backbone model is frozen or not should not make too much difference if it's passed as an argument to the forward function.

**Comment by cuongnguyengit** [comment]
Thanks. One more question: with IMO model, for similar epochs, will you
approach converge more slowly? I just tried on 3 epochs on my data

Vào Th 4, 29 thg 5, 2024 lúc 15:36 WilliamsToTo ***@***.***>
đã viết:

**Comment by WilliamsToTo** [comment]
I'm glad to hear that the code is running smoothly. Regarding your question, I don't recall whether the IMO coverage was slower or faster compared to other models. Unfortunately, I did not record that information during the experiment.
