### ISSUE TITLE
CausalScore github

### ISSUE THREAD

**Issue by hppy139** [WilliamsToTo/IMG#2]
Hello, I'm interested in the paper <CausalScore: An Automatic Reference-Free Metric for Assessing Response Relevance in Open-Domain Dialogue Systems>, and I wonder how to reproduce the performance in it.
"Codes and datasets are available at (https://github.com/WilliamsToTo/causalscore_dialogue)." But it's hard for me to get, can you share it? THX.

**Comment by WilliamsToTo** [comment]
The paper is under review so I make the repo private. You can get the code [here](https://anonymous.4open.science/r/causalscore_dialogue-7C03).
